name: mol4eng
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - joblib=1.3.2
  - jupyter=1.0.0
  - matplotlib=3.8.3
  - networkx=3.2.1
  - numpy=1.26.4
  - pandas=2.2.1
  - pip=24.0
  - pycairo=1.23.0
  - python=3.10.13
  - python-graphviz=0.20.1
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - pyyaml=6.0.1
  - rdkit=2023.03.3
  - requests=2.31.0
  - tqdm=4.66.2
  - yaml=0.2.5
  - scikit-learn=1.4.2
  - pip:
      - fastapi==0.111.0
      - pebble==5.0.6
      - pydantic==1.10.12
      - pymongo==4.6.2
      - python-json-logger==2.0.7
      - scipy==1.13.1
      - pytorch_lightning==1.9.5
      - torch_geometric==2.3.1
      - seaborn==0.13.2
      - git+https://github.com/keiserlab/e3fp.git
